[package]
name = "rusty-sockets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22.0"
eframe = "0.22.0"
egui_dock = "0.6.3"
anyhow = "1"
flume = "0.11"